# Generated by Django 6.0.4 on 2026-05-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buglog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='buglog',
            name='ai_analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buglog',
            name='parsed_error',
            field=models.TextField(),
        ),
    ]
